/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package  ProyectoInidvidualSarasola.codigo;

//import aed1.obligatorio2016.catedra.*;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;
import javax.swing.plaf.basic.BasicListUI;
import sun.misc.Perf;

/**
 *
 * @author Josse
 */
public class UCUMovieFrame extends javax.swing.JFrame {
    IGestorDeContenidos UCUMovieGestor;
    
    /**
     * Creates new form AEDIMovieFrame
     */
    public UCUMovieFrame() {
        UCUMovieGestor = new GestorDeContenidosUCUMovie();
        initComponents();
        jTabbedPanePrincipal.setVisible(false);
        
        this.setLocationRelativeTo(UCUMovieFrame.this);
        this.setExtendedState(UCUMovieFrame.MAXIMIZED_BOTH);
        this.setTitle("UCU MOVIE");
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCargar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTabbedPanePrincipal = new javax.swing.JTabbedPane();
        jPanelPaginaInicio = new javax.swing.JPanel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelImagenPeliculaEstreno2 = new javax.swing.JLabel();
        jLabelImagenPeliculaEstreno1 = new javax.swing.JLabel();
        jLabelNombreEstreno1 = new javax.swing.JLabel();
        jLabelNombreEstreno2 = new javax.swing.JLabel();
        jLabelAnioEstreno1 = new javax.swing.JLabel();
        jLabelPuntuacionEstreno1 = new javax.swing.JLabel();
        jLabelAnioEstreno2 = new javax.swing.JLabel();
        jLabelPuntuacionEstreno2 = new javax.swing.JLabel();
        jLabelEstrenoPuntaje = new javax.swing.JLabel();
        jLabelUcuMovies = new javax.swing.JLabel();
        jLabelEstrenoPuntaje1 = new javax.swing.JLabel();
        jLabelEstrenos1 = new javax.swing.JLabel();
        jPanelPrincipalPeliculas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPeliculas = new javax.swing.JList();
        jLabelTodasLasPeliculas = new javax.swing.JLabel();
        jPanelBusquedaActores = new javax.swing.JPanel();
        jPanelBusquedaPorActor = new javax.swing.JPanel();
        jComboBoxActores = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListResultBusquedaActores = new javax.swing.JList<>();
        jLabelBusquedaActores = new javax.swing.JLabel();
        jPanelBusquedaPorGenero = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListResultBusquedaGenero = new javax.swing.JList<>();
        jLabelBusquedaPorGenero = new javax.swing.JLabel();
        jPanelBusquedaAnio = new javax.swing.JPanel();
        jPanelBusquedaPorAnio = new javax.swing.JPanel();
        jComboBoxAnioSuperior = new javax.swing.JComboBox<>();
        jComboBoxAnioInferior = new javax.swing.JComboBox<>();
        jButtonBuscarPorAnio = new javax.swing.JButton();
        jLabelBusquedaAnioDesde = new javax.swing.JLabel();
        jLabelBusquedaAnioDesde1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListResultBusquedaAnio = new javax.swing.JList<>();
        jLabelBusquedaPorAnio = new javax.swing.JLabel();
        jPanelBusquedaPorPuntaje = new javax.swing.JPanel();
        jPanelBusquedaPorAnio1 = new javax.swing.JPanel();
        jComboBoxPuntajeSuperior = new javax.swing.JComboBox<>();
        jComboBoxPuntajeInferior = new javax.swing.JComboBox<>();
        jButtonBuscarPorPuntaje = new javax.swing.JButton();
        jLabelBusquedaPuntajeDesde = new javax.swing.JLabel();
        jLabelBusquedaPuntajeHasta = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jListResultBusquedaPuntaje = new javax.swing.JList<>();
        jLabelBuscarPorPuntaje = new javax.swing.JLabel();
        jPanelBusquedaGeneral = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListResultBusqueda = new javax.swing.JList<>();
        jPanelBusquedaPorDirector1 = new javax.swing.JPanel();
        jComboBoxDirectores1 = new javax.swing.JComboBox<>();
        jLabelBusquedaGeneralDirector = new javax.swing.JLabel();
        jPanelBusquedaPorActor1 = new javax.swing.JPanel();
        jComboBoxActores1 = new javax.swing.JComboBox<>();
        jLabelBusquedaGeneralActor = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jComboBoxGenero1 = new javax.swing.JComboBox<>();
        jLabelBusquedaGeneralGenero = new javax.swing.JLabel();
        jPanelBusquedaPorAnio2 = new javax.swing.JPanel();
        jComboBoxAnioSuperior1 = new javax.swing.JComboBox<>();
        jComboBoxAnioInferior1 = new javax.swing.JComboBox<>();
        jLabelBusquedaAnioDesdeGeneral = new javax.swing.JLabel();
        jLabelBusquedaAnioHastaGeneral = new javax.swing.JLabel();
        jPanelBusquedaPorAnio3 = new javax.swing.JPanel();
        jComboBoxPuntajeSuperior1 = new javax.swing.JComboBox<>();
        jComboBoxPuntajeInferior1 = new javax.swing.JComboBox<>();
        jLabelBusquedaPuntajeDesdeGeneral = new javax.swing.JLabel();
        jLabelBusquedaPuntajeHasta1 = new javax.swing.JLabel();
        jButtonBusquedaCriteriosVarios = new javax.swing.JButton();
        jLabelBusquedaGeneral = new javax.swing.JLabel();
        jPanelBusquedaDirectores = new javax.swing.JPanel();
        jPanelBusquedaPorDirector = new javax.swing.JPanel();
        jComboBoxDirectores = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListResultBusquedaDirectores = new javax.swing.JList<>();
        jLabelBusquedaDirector = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setIconImages(null);

        jButtonCargar.setText("CARGAR APLICACIÓN");
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });

        jPanelPaginaInicio.setBackground(new java.awt.Color(204, 204, 204));

        jLabelInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoInidvidualSarasola/ImagenesPermanentes/UCUMovieIcon.png"))); // NOI18N

        jLabelImagenPeliculaEstreno2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabelImagenPeliculaEstreno2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImagenPeliculaEstreno2MouseClicked(evt);
            }
        });

        jLabelImagenPeliculaEstreno1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabelImagenPeliculaEstreno1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImagenPeliculaEstreno1MouseClicked(evt);
            }
        });

        jLabelNombreEstreno1.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabelNombreEstreno1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreEstreno1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabelNombreEstreno1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelNombreEstreno2.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabelNombreEstreno2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreEstreno2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabelNombreEstreno2.setFocusable(false);
        jLabelNombreEstreno2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelAnioEstreno1.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabelAnioEstreno1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnioEstreno1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabelAnioEstreno1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelPuntuacionEstreno1.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabelPuntuacionEstreno1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPuntuacionEstreno1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabelPuntuacionEstreno1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelAnioEstreno2.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabelAnioEstreno2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnioEstreno2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabelAnioEstreno2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelPuntuacionEstreno2.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabelPuntuacionEstreno2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPuntuacionEstreno2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabelPuntuacionEstreno2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelEstrenoPuntaje.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabelEstrenoPuntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstrenoPuntaje.setText("AÑO");
        jLabelEstrenoPuntaje.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelEstrenoPuntaje.setFocusable(false);
        jLabelEstrenoPuntaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelUcuMovies.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabelUcuMovies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUcuMovies.setText("UCU MOVIES");
        jLabelUcuMovies.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelUcuMovies.setFocusable(false);
        jLabelUcuMovies.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelEstrenoPuntaje1.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabelEstrenoPuntaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstrenoPuntaje1.setText("PUNTAJE");
        jLabelEstrenoPuntaje1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelEstrenoPuntaje1.setFocusable(false);
        jLabelEstrenoPuntaje1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelEstrenos1.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabelEstrenos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstrenos1.setText("ESTRENOS");
        jLabelEstrenos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelEstrenos1.setFocusable(false);
        jLabelEstrenos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelPaginaInicioLayout = new javax.swing.GroupLayout(jPanelPaginaInicio);
        jPanelPaginaInicio.setLayout(jPanelPaginaInicioLayout);
        jPanelPaginaInicioLayout.setHorizontalGroup(
            jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaginaInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaginaInicioLayout.createSequentialGroup()
                        .addComponent(jLabelInicio)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaginaInicioLayout.createSequentialGroup()
                        .addComponent(jLabelUcuMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addComponent(jLabelImagenPeliculaEstreno2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanelPaginaInicioLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPuntuacionEstreno1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAnioEstreno1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreEstreno1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEstrenoPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstrenoPuntaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstrenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaginaInicioLayout.createSequentialGroup()
                        .addComponent(jLabelNombreEstreno2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(jPanelPaginaInicioLayout.createSequentialGroup()
                        .addGroup(jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPuntuacionEstreno2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAnioEstreno2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPaginaInicioLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jLabelImagenPeliculaEstreno1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(800, Short.MAX_VALUE)))
        );
        jPanelPaginaInicioLayout.setVerticalGroup(
            jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaginaInicioLayout.createSequentialGroup()
                .addGroup(jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPaginaInicioLayout.createSequentialGroup()
                        .addGroup(jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPaginaInicioLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabelUcuMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabelInicio))
                            .addGroup(jPanelPaginaInicioLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabelImagenPeliculaEstreno2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNombreEstreno2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEstrenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelNombreEstreno1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPaginaInicioLayout.createSequentialGroup()
                        .addComponent(jLabelEstrenoPuntaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEstrenoPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelPaginaInicioLayout.createSequentialGroup()
                            .addComponent(jLabelPuntuacionEstreno1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelAnioEstreno1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelPaginaInicioLayout.createSequentialGroup()
                            .addComponent(jLabelPuntuacionEstreno2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAnioEstreno2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(jPanelPaginaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPaginaInicioLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabelImagenPeliculaEstreno1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(214, Short.MAX_VALUE)))
        );

        jTabbedPanePrincipal.addTab("         INICIO         ", jPanelPaginaInicio);

        jPanelPrincipalPeliculas.setBackground(new java.awt.Color(204, 204, 204));
        jPanelPrincipalPeliculas.setLayout(null);

        jListPeliculas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jListPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPeliculasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListPeliculas);

        jPanelPrincipalPeliculas.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 550, 660);

        jLabelTodasLasPeliculas.setBackground(new java.awt.Color(204, 204, 204));
        jLabelTodasLasPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoInidvidualSarasola/ImagenesPermanentes/TodasLasPeliculas.png"))); // NOI18N
        jPanelPrincipalPeliculas.add(jLabelTodasLasPeliculas);
        jLabelTodasLasPeliculas.setBounds(180, 30, 1080, 700);

        jTabbedPanePrincipal.addTab("TODAS LAS PELÍCULAS", jPanelPrincipalPeliculas);

        jPanelBusquedaActores.setBackground(new java.awt.Color(204, 204, 204));
        jPanelBusquedaActores.setLayout(null);

        jPanelBusquedaPorActor.setBackground(new java.awt.Color(153, 153, 153));
        jPanelBusquedaPorActor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBoxActores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBusquedaPorActorLayout = new javax.swing.GroupLayout(jPanelBusquedaPorActor);
        jPanelBusquedaPorActor.setLayout(jPanelBusquedaPorActorLayout);
        jPanelBusquedaPorActorLayout.setHorizontalGroup(
            jPanelBusquedaPorActorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPorActorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jComboBoxActores, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanelBusquedaPorActorLayout.setVerticalGroup(
            jPanelBusquedaPorActorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPorActorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jComboBoxActores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jPanelBusquedaActores.add(jPanelBusquedaPorActor);
        jPanelBusquedaPorActor.setBounds(650, 30, 220, 122);

        jListResultBusquedaActores.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jListResultBusquedaActores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListResultBusquedaActoresMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jListResultBusquedaActores);

        jPanelBusquedaActores.add(jScrollPane5);
        jScrollPane5.setBounds(40, 30, 350, 640);

        jLabelBusquedaActores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoInidvidualSarasola/ImagenesPermanentes/BusquedaActores.png"))); // NOI18N
        jPanelBusquedaActores.add(jLabelBusquedaActores);
        jLabelBusquedaActores.setBounds(120, 0, 1080, 670);

        jTabbedPanePrincipal.addTab("   BÚSQUEDA POR ACTOR   ", jPanelBusquedaActores);

        jPanelBusquedaPorGenero.setBackground(new java.awt.Color(204, 204, 204));
        jPanelBusquedaPorGenero.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanelBusquedaPorGenero.add(jPanel1);
        jPanel1.setBounds(220, 70, 254, 110);

        jListResultBusquedaGenero.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jListResultBusquedaGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListResultBusquedaGeneroMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jListResultBusquedaGenero);

        jPanelBusquedaPorGenero.add(jScrollPane6);
        jScrollPane6.setBounds(690, 30, 510, 660);

        jLabelBusquedaPorGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoInidvidualSarasola/ImagenesPermanentes/BusquedaGeneros.png"))); // NOI18N
        jPanelBusquedaPorGenero.add(jLabelBusquedaPorGenero);
        jLabelBusquedaPorGenero.setBounds(6, 0, 1190, 670);

        jTabbedPanePrincipal.addTab("     BÚSQUEDA POR GÉNERO", jPanelBusquedaPorGenero);

        jPanelBusquedaAnio.setBackground(new java.awt.Color(204, 204, 204));
        jPanelBusquedaAnio.setLayout(null);

        jPanelBusquedaPorAnio.setBackground(new java.awt.Color(153, 153, 153));
        jPanelBusquedaPorAnio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBoxAnioSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnioSuperiorActionPerformed(evt);
            }
        });

        jComboBoxAnioInferior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnioInferiorActionPerformed(evt);
            }
        });

        jButtonBuscarPorAnio.setText("Buscar");
        jButtonBuscarPorAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPorAnioActionPerformed(evt);
            }
        });

        jLabelBusquedaAnioDesde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusquedaAnioDesde.setText("DESDE:");
        jLabelBusquedaAnioDesde.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelBusquedaAnioDesde.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelBusquedaAnioDesde1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusquedaAnioDesde1.setText("HASTA:");
        jLabelBusquedaAnioDesde1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelBusquedaAnioDesde1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelBusquedaPorAnioLayout = new javax.swing.GroupLayout(jPanelBusquedaPorAnio);
        jPanelBusquedaPorAnio.setLayout(jPanelBusquedaPorAnioLayout);
        jPanelBusquedaPorAnioLayout.setHorizontalGroup(
            jPanelBusquedaPorAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPorAnioLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanelBusquedaPorAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxAnioInferior, 0, 125, Short.MAX_VALUE)
                    .addComponent(jButtonBuscarPorAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jLabelBusquedaAnioDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelBusquedaAnioDesde1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxAnioSuperior, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelBusquedaPorAnioLayout.setVerticalGroup(
            jPanelBusquedaPorAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaPorAnioLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabelBusquedaAnioDesde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxAnioInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabelBusquedaAnioDesde1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxAnioSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonBuscarPorAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelBusquedaAnio.add(jPanelBusquedaPorAnio);
        jPanelBusquedaPorAnio.setBounds(680, 420, 250, 270);

        jListResultBusquedaAnio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jListResultBusquedaAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListResultBusquedaAnioMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jListResultBusquedaAnio);

        jPanelBusquedaAnio.add(jScrollPane7);
        jScrollPane7.setBounds(40, 30, 360, 640);

        jLabelBusquedaPorAnio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoInidvidualSarasola/ImagenesPermanentes/BusquedaPorAnios.png"))); // NOI18N
        jPanelBusquedaAnio.add(jLabelBusquedaPorAnio);
        jLabelBusquedaPorAnio.setBounds(90, 0, 1110, 710);

        jTabbedPanePrincipal.addTab("     BÚSQUEDA POR AÑO   ", jPanelBusquedaAnio);

        jPanelBusquedaPorPuntaje.setBackground(new java.awt.Color(204, 204, 204));
        jPanelBusquedaPorPuntaje.setLayout(null);

        jPanelBusquedaPorAnio1.setBackground(new java.awt.Color(153, 153, 153));
        jPanelBusquedaPorAnio1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBoxPuntajeSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPuntajeSuperiorActionPerformed(evt);
            }
        });

        jComboBoxPuntajeInferior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPuntajeInferiorActionPerformed(evt);
            }
        });

        jButtonBuscarPorPuntaje.setText("Buscar");
        jButtonBuscarPorPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPorPuntajeActionPerformed(evt);
            }
        });

        jLabelBusquedaPuntajeDesde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusquedaPuntajeDesde.setText("DESDE:");
        jLabelBusquedaPuntajeDesde.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelBusquedaPuntajeDesde.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelBusquedaPuntajeHasta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusquedaPuntajeHasta.setText("HASTA:");
        jLabelBusquedaPuntajeHasta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelBusquedaPuntajeHasta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelBusquedaPorAnio1Layout = new javax.swing.GroupLayout(jPanelBusquedaPorAnio1);
        jPanelBusquedaPorAnio1.setLayout(jPanelBusquedaPorAnio1Layout);
        jPanelBusquedaPorAnio1Layout.setHorizontalGroup(
            jPanelBusquedaPorAnio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPorAnio1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelBusquedaPorAnio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxPuntajeInferior, 0, 125, Short.MAX_VALUE)
                    .addComponent(jComboBoxPuntajeSuperior, 0, 125, Short.MAX_VALUE)
                    .addComponent(jButtonBuscarPorPuntaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelBusquedaPuntajeDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelBusquedaPuntajeHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        jPanelBusquedaPorAnio1Layout.setVerticalGroup(
            jPanelBusquedaPorAnio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaPorAnio1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelBusquedaPuntajeDesde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxPuntajeInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabelBusquedaPuntajeHasta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxPuntajeSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButtonBuscarPorPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanelBusquedaPorPuntaje.add(jPanelBusquedaPorAnio1);
        jPanelBusquedaPorAnio1.setBounds(390, 360, 229, 280);

        jListResultBusquedaPuntaje.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jListResultBusquedaPuntaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListResultBusquedaPuntajeMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jListResultBusquedaPuntaje);

        jPanelBusquedaPorPuntaje.add(jScrollPane8);
        jScrollPane8.setBounds(820, 40, 390, 640);

        jLabelBuscarPorPuntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoInidvidualSarasola/ImagenesPermanentes/BusquedaPorPuntos.png"))); // NOI18N
        jPanelBusquedaPorPuntaje.add(jLabelBuscarPorPuntaje);
        jLabelBuscarPorPuntaje.setBounds(0, 0, 1150, 680);

        jTabbedPanePrincipal.addTab("BÚSQUEDA POR PUNTAJE", jPanelBusquedaPorPuntaje);

        jPanelBusquedaGeneral.setBackground(new java.awt.Color(204, 204, 204));
        jPanelBusquedaGeneral.setLayout(null);

        jListResultBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jListResultBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListResultBusquedaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListResultBusqueda);

        jPanelBusquedaGeneral.add(jScrollPane3);
        jScrollPane3.setBounds(860, 20, 360, 680);

        jPanelBusquedaPorDirector1.setBackground(new java.awt.Color(153, 153, 153));
        jPanelBusquedaPorDirector1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelBusquedaGeneralDirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusquedaGeneralDirector.setText("DIRECTOR:");
        jLabelBusquedaGeneralDirector.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelBusquedaGeneralDirector.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelBusquedaPorDirector1Layout = new javax.swing.GroupLayout(jPanelBusquedaPorDirector1);
        jPanelBusquedaPorDirector1.setLayout(jPanelBusquedaPorDirector1Layout);
        jPanelBusquedaPorDirector1Layout.setHorizontalGroup(
            jPanelBusquedaPorDirector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaPorDirector1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanelBusquedaPorDirector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelBusquedaGeneralDirector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxDirectores1, 0, 151, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanelBusquedaPorDirector1Layout.setVerticalGroup(
            jPanelBusquedaPorDirector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaPorDirector1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabelBusquedaGeneralDirector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDirectores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanelBusquedaGeneral.add(jPanelBusquedaPorDirector1);
        jPanelBusquedaPorDirector1.setBounds(580, 20, 255, 110);

        jPanelBusquedaPorActor1.setBackground(new java.awt.Color(153, 153, 153));
        jPanelBusquedaPorActor1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelBusquedaGeneralActor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusquedaGeneralActor.setText("ACTOR:");
        jLabelBusquedaGeneralActor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelBusquedaGeneralActor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelBusquedaPorActor1Layout = new javax.swing.GroupLayout(jPanelBusquedaPorActor1);
        jPanelBusquedaPorActor1.setLayout(jPanelBusquedaPorActor1Layout);
        jPanelBusquedaPorActor1Layout.setHorizontalGroup(
            jPanelBusquedaPorActor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPorActor1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelBusquedaPorActor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelBusquedaGeneralActor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxActores1, 0, 145, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanelBusquedaPorActor1Layout.setVerticalGroup(
            jPanelBusquedaPorActor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPorActor1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelBusquedaGeneralActor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxActores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelBusquedaGeneral.add(jPanelBusquedaPorActor1);
        jPanelBusquedaPorActor1.setBounds(10, 20, 249, 96);

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelBusquedaGeneralGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusquedaGeneralGenero.setText("GÉNERO:");
        jLabelBusquedaGeneralGenero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelBusquedaGeneralGenero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelBusquedaGeneralGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxGenero1, 0, 150, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabelBusquedaGeneralGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxGenero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanelBusquedaGeneral.add(jPanel10);
        jPanel10.setBounds(300, 20, 254, 110);

        jPanelBusquedaPorAnio2.setBackground(new java.awt.Color(153, 153, 153));
        jPanelBusquedaPorAnio2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBoxAnioInferior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnioInferior1ActionPerformed(evt);
            }
        });

        jLabelBusquedaAnioDesdeGeneral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusquedaAnioDesdeGeneral.setText("DE AÑO:");
        jLabelBusquedaAnioDesdeGeneral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelBusquedaAnioDesdeGeneral.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelBusquedaAnioHastaGeneral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusquedaAnioHastaGeneral.setText("HASTA:");
        jLabelBusquedaAnioHastaGeneral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelBusquedaAnioHastaGeneral.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelBusquedaPorAnio2Layout = new javax.swing.GroupLayout(jPanelBusquedaPorAnio2);
        jPanelBusquedaPorAnio2.setLayout(jPanelBusquedaPorAnio2Layout);
        jPanelBusquedaPorAnio2Layout.setHorizontalGroup(
            jPanelBusquedaPorAnio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPorAnio2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelBusquedaPorAnio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelBusquedaAnioDesdeGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxAnioInferior1, 0, 125, Short.MAX_VALUE)
                    .addComponent(jComboBoxAnioSuperior1, 0, 125, Short.MAX_VALUE)
                    .addComponent(jLabelBusquedaAnioHastaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanelBusquedaPorAnio2Layout.setVerticalGroup(
            jPanelBusquedaPorAnio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaPorAnio2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBusquedaAnioDesdeGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxAnioInferior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabelBusquedaAnioHastaGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxAnioSuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelBusquedaGeneral.add(jPanelBusquedaPorAnio2);
        jPanelBusquedaPorAnio2.setBounds(600, 150, 229, 168);

        jPanelBusquedaPorAnio3.setBackground(new java.awt.Color(153, 153, 153));
        jPanelBusquedaPorAnio3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBoxPuntajeInferior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPuntajeInferior1ActionPerformed(evt);
            }
        });

        jLabelBusquedaPuntajeDesdeGeneral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusquedaPuntajeDesdeGeneral.setText("DE PUNTAJE:");
        jLabelBusquedaPuntajeDesdeGeneral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelBusquedaPuntajeDesdeGeneral.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelBusquedaPuntajeHasta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBusquedaPuntajeHasta1.setText("HASTA:");
        jLabelBusquedaPuntajeHasta1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelBusquedaPuntajeHasta1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelBusquedaPorAnio3Layout = new javax.swing.GroupLayout(jPanelBusquedaPorAnio3);
        jPanelBusquedaPorAnio3.setLayout(jPanelBusquedaPorAnio3Layout);
        jPanelBusquedaPorAnio3Layout.setHorizontalGroup(
            jPanelBusquedaPorAnio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPorAnio3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelBusquedaPorAnio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelBusquedaPuntajeDesdeGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxPuntajeInferior1, 0, 125, Short.MAX_VALUE)
                    .addComponent(jComboBoxPuntajeSuperior1, 0, 125, Short.MAX_VALUE)
                    .addComponent(jLabelBusquedaPuntajeHasta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanelBusquedaPorAnio3Layout.setVerticalGroup(
            jPanelBusquedaPorAnio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaPorAnio3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabelBusquedaPuntajeDesdeGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxPuntajeInferior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelBusquedaPuntajeHasta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxPuntajeSuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelBusquedaGeneral.add(jPanelBusquedaPorAnio3);
        jPanelBusquedaPorAnio3.setBounds(10, 150, 229, 168);

        jButtonBusquedaCriteriosVarios.setText("Buscar");
        jButtonBusquedaCriteriosVarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaCriteriosVariosActionPerformed(evt);
            }
        });
        jPanelBusquedaGeneral.add(jButtonBusquedaCriteriosVarios);
        jButtonBusquedaCriteriosVarios.setBounds(340, 220, 150, 50);

        jLabelBusquedaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoInidvidualSarasola/ImagenesPermanentes/BusquedaGeneral.png"))); // NOI18N
        jPanelBusquedaGeneral.add(jLabelBusquedaGeneral);
        jLabelBusquedaGeneral.setBounds(0, 0, 1240, 710);

        jTabbedPanePrincipal.addTab("BÚSQUEDA GENERAL", jPanelBusquedaGeneral);

        jPanelBusquedaDirectores.setBackground(new java.awt.Color(204, 204, 204));
        jPanelBusquedaDirectores.setLayout(null);

        jPanelBusquedaPorDirector.setBackground(new java.awt.Color(153, 153, 153));
        jPanelBusquedaPorDirector.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBoxDirectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDirectoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBusquedaPorDirectorLayout = new javax.swing.GroupLayout(jPanelBusquedaPorDirector);
        jPanelBusquedaPorDirector.setLayout(jPanelBusquedaPorDirectorLayout);
        jPanelBusquedaPorDirectorLayout.setHorizontalGroup(
            jPanelBusquedaPorDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPorDirectorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jComboBoxDirectores, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanelBusquedaPorDirectorLayout.setVerticalGroup(
            jPanelBusquedaPorDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPorDirectorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jComboBoxDirectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jPanelBusquedaDirectores.add(jPanelBusquedaPorDirector);
        jPanelBusquedaPorDirector.setBounds(330, 60, 255, 120);

        jListResultBusquedaDirectores.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jListResultBusquedaDirectores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListResultBusquedaDirectoresMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jListResultBusquedaDirectores);

        jPanelBusquedaDirectores.add(jScrollPane4);
        jScrollPane4.setBounds(790, 30, 400, 640);

        jLabelBusquedaDirector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoInidvidualSarasola/ImagenesPermanentes/BusquedaDirectores.png"))); // NOI18N
        jPanelBusquedaDirectores.add(jLabelBusquedaDirector);
        jLabelBusquedaDirector.setBounds(0, 0, 1080, 670);

        jTabbedPanePrincipal.addTab("BUSQUEDA POR DIRECTOR", jPanelBusquedaDirectores);

        jLayeredPane1.setLayer(jTabbedPanePrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPanePrincipal)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPanePrincipal.getAccessibleContext().setAccessibleName("BÚSQUEDA POR DIRECTOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButtonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarActionPerformed
        
        jButtonCargar.setVisible(false);
        UCUMovieGestor.cargarDatos
        ("src/ProyectoInidvidualSarasola/archivos/Big-Peliculas.csv",
         "src/ProyectoInidvidualSarasola/archivos/Big-Actores.csv",
         "src/ProyectoInidvidualSarasola/archivos/Big-Directores.csv",
         "src/ProyectoInidvidualSarasola/archivos/Big-Productores.csv",
         "src/ProyectoInidvidualSarasola/archivos/Big-PeliculasActores.csv",
         "src/ProyectoInidvidualSarasola/archivos/Big-PeliculasDirectores.csv",
         "src/ProyectoInidvidualSarasola/archivos/Big-PeliculasProductores.csv",
         "src/ProyectoInidvidualSarasola/archivos/Big-Imagenes.csv");
        jTabbedPanePrincipal.setVisible(true);        
        /*Cargo las películas al jListPeliculas
        */
        
        
        ILista<Pelicula> listaPeliculas = UCUMovieGestor.obtenerPeliculas();
        DefaultListModel model = new DefaultListModel();
        jListPeliculas.setModel(model);
        INodo<Pelicula> auxiliarPelicula = listaPeliculas.getPrimero();        
        while (auxiliarPelicula != null){
            String a = auxiliarPelicula.getDato().getNombre();
            model.addElement(a);
            auxiliarPelicula = auxiliarPelicula.getSiguiente();
        }        
        /*
         *Cargo los directores al jComboBoxDirectores.
        */
        ILista<Director> listaDirectores = UCUMovieGestor.obtenerDirectores();        
        INodo<Director> auxiliarDirector = listaDirectores.getPrimero();        
        while (auxiliarDirector != null){
            String a = auxiliarDirector.getDato().getNombre();
            jComboBoxDirectores.addItem(a);            
            jComboBoxDirectores1.addItem(a);            
            auxiliarDirector = auxiliarDirector.getSiguiente();
        }
        /*
         *Cargo los Actores al jComboBoxActores
        */
        ILista<Actor> listaActores = UCUMovieGestor.obtenerActores();        
        INodo<Actor> auxiliarActores = listaActores.getPrimero();        
        while (auxiliarActores != null){
            String a = auxiliarActores.getDato().getNombre();
            jComboBoxActores.addItem(a);
            jComboBoxActores1.addItem(a);
            auxiliarActores = auxiliarActores.getSiguiente();
        }
        /*Cargo el jComboBoxAnioInferior con los años para realizar una 
         *búsqueda.
         *Año de pelicula mas antigua en la base de datos.*/
        int anioInicial = UCUMovieGestor.obtenerAnioPeliculaMasAntigua();
        /*
         *Obtengo el año actual del sistema.
        */
        Calendar calendario = Calendar.getInstance();        
        int anioActual = calendario.get(Calendar.YEAR);        
        
        for (int i = anioInicial; i <= anioActual; i++) {
            String aIngresar =  ""+i;
            jComboBoxAnioInferior.addItem(aIngresar);            
            jComboBoxAnioInferior1.addItem(aIngresar);            
        }
        
        /*
         *Cargo los Generos al jComboBoxGenero.
        */
        Lista listaGeneros = UCUMovieGestor.generosEnListaPeliculas();        
        INodo<String> auxiliar = listaGeneros.getPrimero();        
        while (auxiliar != null){
            String a = auxiliar.getDato();
            jComboBoxGenero.addItem(a);
            jComboBoxGenero1.addItem(a);
            auxiliar = auxiliar.getSiguiente();
        }
        
        /*
         *Cargo el jComboBoxPuntajeInferior con los años para realizar una
         *búsqueda.
        */
        int puntajeInicial = 0;      
        for (int i = puntajeInicial; i <= 10; i++) {
            String aIngresar =  ""+i;
            jComboBoxPuntajeInferior.addItem(aIngresar);            
            jComboBoxPuntajeInferior1.addItem(aIngresar);            
        }
        /*
         *Cargo Estrenos.
        */
        INodo<Pelicula> auxiliarPelicula1;
        auxiliarPelicula1 = UCUMovieGestor.obtenerPeliculas().getPrimero();
        int contador = 0;
        while(auxiliarPelicula1 != null && contador <= 1){
            String rutaAImagen;
            rutaAImagen = UCUMovieGestor.imagenPelicula(auxiliarPelicula1.
                                                         getDato().getNombre());            
            ImageIcon imagenIcono = new ImageIcon(rutaAImagen);
            if (contador == 0){
                Icon icono = new ImageIcon(imagenIcono.getImage().
                      getScaledInstance(jLabelImagenPeliculaEstreno1.getWidth(),
                            jLabelImagenPeliculaEstreno2.getHeight(), 
                                        Image.SCALE_DEFAULT));
                this.jLabelImagenPeliculaEstreno1.setIcon(icono);
                this.jLabelNombreEstreno1.setText(auxiliarPelicula1.
                                                    getDato().getNombre());
                this.jLabelPuntuacionEstreno1.setText(""+auxiliarPelicula1.
                                                        getDato().getPuntaje());
                this.jLabelAnioEstreno1.setText(""+auxiliarPelicula1.
                                                           getDato().getAnio());
            }else{
                Icon icono = new ImageIcon(imagenIcono.getImage().
                      getScaledInstance(jLabelImagenPeliculaEstreno2.getWidth(),
                              jLabelImagenPeliculaEstreno2.getHeight(), 
                                         Image.SCALE_DEFAULT));
                this.jLabelImagenPeliculaEstreno2.setIcon(icono);
                this.jLabelNombreEstreno2.setText(auxiliarPelicula1.
                                                    getDato().getNombre());
                this.jLabelPuntuacionEstreno2.setText(""+auxiliarPelicula1.
                                                        getDato().getPuntaje());
                this.jLabelAnioEstreno2.setText(""+auxiliarPelicula1.
                                                           getDato().getAnio());
            }
            contador++;
            auxiliarPelicula1 = auxiliarPelicula1.getSiguiente();            
        }        
                
    }//GEN-LAST:event_jButtonCargarActionPerformed

    private void jListPeliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPeliculasMouseClicked
        String selected = (String)jListPeliculas.getSelectedValue();
        
        if (selected!=null){            
            String rutaAImagen = UCUMovieGestor.imagenPelicula(selected);
            InfoPeliculaDetallada infopelicula;         
            infopelicula = new InfoPeliculaDetallada
                     (UCUMovieGestor.infoPelicula(selected), this, rutaAImagen);
            infopelicula.setVisible(true);            
        }  
    }//GEN-LAST:event_jListPeliculasMouseClicked

    private void jComboBoxDirectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDirectoresActionPerformed
       
        String selected = jComboBoxDirectores.getSelectedItem().toString();        
        Lista listaPeliculas = UCUMovieGestor.peliculasDeDirector(selected);        

        DefaultListModel model = new DefaultListModel();
        jListResultBusquedaDirectores.setModel(model);        
        
        INodo<Pelicula> auxiliar = listaPeliculas.getPrimero();        
        while (auxiliar != null){
            String a = auxiliar.getDato().getNombre();
            model.addElement(a);
            auxiliar = auxiliar.getSiguiente();
        } 
    }//GEN-LAST:event_jComboBoxDirectoresActionPerformed

    private void jComboBoxActoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActoresActionPerformed
               
        String selected = jComboBoxActores.getSelectedItem().toString();        
        Lista listaPeliculas = UCUMovieGestor.peliculasDeActor(selected);        

        DefaultListModel model = new DefaultListModel();
        jListResultBusquedaActores.setModel(model);        
        
        INodo<Pelicula> auxiliar = listaPeliculas.getPrimero();        
        while (auxiliar != null){
            String a = auxiliar.getDato().getNombre();
            model.addElement(a);
            auxiliar = auxiliar.getSiguiente();
        } 
    }//GEN-LAST:event_jComboBoxActoresActionPerformed
    
    
    private void jComboBoxAnioInferiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnioInferiorActionPerformed
              
        int anioInicioBusqueda;        
        anioInicioBusqueda = Integer.parseInt((String)jComboBoxAnioInferior.
                                                            getSelectedItem());
        /*
         *Obtengo el año actual del sistema.
        */
        Calendar calendario = Calendar.getInstance();        
        int anioActual = calendario.get(Calendar.YEAR);
        
        jComboBoxAnioSuperior.removeAllItems();
        for (int i = anioInicioBusqueda; i <= anioActual; i++) {
            String aIngresar =  ""+i;
            jComboBoxAnioSuperior.addItem(aIngresar);            
        }
    }//GEN-LAST:event_jComboBoxAnioInferiorActionPerformed

    private void jComboBoxAnioSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnioSuperiorActionPerformed
          jButtonBuscarPorAnio.setVisible(true);
       
    }//GEN-LAST:event_jComboBoxAnioSuperiorActionPerformed
   
    private void jButtonBuscarPorAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPorAnioActionPerformed
        int anioInicioBusqueda; 
        anioInicioBusqueda = Integer.parseInt((String)jComboBoxAnioInferior.
                                                            getSelectedItem());
        int anioFinalBusqueda;       
        anioFinalBusqueda = Integer.parseInt((String)jComboBoxAnioSuperior.
                                                            getSelectedItem());
        
        Lista listaPeliculas;        
        listaPeliculas = UCUMovieGestor.peliculasPorAnio(anioInicioBusqueda, 
                                                            anioFinalBusqueda);

        DefaultListModel model = new DefaultListModel();
        jListResultBusquedaAnio.setModel(model);        
        
        INodo<Pelicula> auxiliar = listaPeliculas.getPrimero();        
        while (auxiliar != null){
            String a = auxiliar.getDato().getNombre();
            model.addElement(a);
            auxiliar = auxiliar.getSiguiente();
        }
    }//GEN-LAST:event_jButtonBuscarPorAnioActionPerformed

    private void jComboBoxPuntajeSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPuntajeSuperiorActionPerformed
        jButtonBuscarPorPuntaje.setVisible(true);
    }//GEN-LAST:event_jComboBoxPuntajeSuperiorActionPerformed

    private void jComboBoxPuntajeInferiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPuntajeInferiorActionPerformed
        
        int puntajeInicioBusqueda;       
        puntajeInicioBusqueda = Integer.parseInt
                           ((String)jComboBoxPuntajeInferior.getSelectedItem());
        jComboBoxPuntajeSuperior.removeAllItems();
        for (int i = puntajeInicioBusqueda; i <= 10; i++) {
            String aIngresar =  ""+i;
            jComboBoxPuntajeSuperior.addItem(aIngresar);            
        }
    }//GEN-LAST:event_jComboBoxPuntajeInferiorActionPerformed

    private void jButtonBuscarPorPuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPorPuntajeActionPerformed
        double puntajeInicioBusqueda; 
        puntajeInicioBusqueda = Double.parseDouble
                           ((String)jComboBoxPuntajeInferior.getSelectedItem());
        double puntajeFinalBusqueda;       
        puntajeFinalBusqueda = Double.parseDouble
                           ((String)jComboBoxPuntajeSuperior.getSelectedItem());
        
        Lista listaPeliculas;        
        listaPeliculas = UCUMovieGestor.peliculasPorPuntaje
                                  (puntajeInicioBusqueda, puntajeFinalBusqueda);

        DefaultListModel model = new DefaultListModel();
        jListResultBusquedaPuntaje.setModel(model);        
        
        INodo<Pelicula> auxiliar = listaPeliculas.getPrimero();        
        while (auxiliar != null){
            String a = auxiliar.getDato().getNombre();
            model.addElement(a);
            auxiliar = auxiliar.getSiguiente();
        }
    }//GEN-LAST:event_jButtonBuscarPorPuntajeActionPerformed

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed
        String selected = jComboBoxGenero.getSelectedItem().toString();        
        Lista listaPeliculas = UCUMovieGestor.peliculasPorGenero(selected);        

        DefaultListModel model = new DefaultListModel();
        jListResultBusquedaGenero.setModel(model);        
        
        INodo<Pelicula> auxiliar = listaPeliculas.getPrimero();        
        while (auxiliar != null){
            String a = auxiliar.getDato().getNombre();
            model.addElement(a);
            auxiliar = auxiliar.getSiguiente();
        } 
    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    private void jComboBoxAnioInferior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnioInferior1ActionPerformed
        int anioInicioBusqueda;        
        anioInicioBusqueda = Integer.parseInt((String)jComboBoxAnioInferior1.
                                                            getSelectedItem());
        /*
         *Obtengo el año actual del sistema.
        */
        Calendar calendario = Calendar.getInstance();        
        int anioActual = calendario.get(Calendar.YEAR);
        
        jComboBoxAnioSuperior1.removeAllItems();
        for (int i = anioInicioBusqueda; i <= anioActual; i++) {
            String aIngresar =  ""+i;
            jComboBoxAnioSuperior1.addItem(aIngresar);            
        }
    }//GEN-LAST:event_jComboBoxAnioInferior1ActionPerformed

    private void jComboBoxPuntajeInferior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPuntajeInferior1ActionPerformed
        int puntajeInicioBusqueda;       
        puntajeInicioBusqueda = Integer.parseInt
                          ((String)jComboBoxPuntajeInferior1.getSelectedItem());
        jComboBoxPuntajeSuperior1.removeAllItems();
        for (int i = puntajeInicioBusqueda; i <= 10; i++) {
            String aIngresar =  ""+i;
            jComboBoxPuntajeSuperior1.addItem(aIngresar);            
        }
    }//GEN-LAST:event_jComboBoxPuntajeInferior1ActionPerformed

    private void jButtonBusquedaCriteriosVariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaCriteriosVariosActionPerformed
        String director = jComboBoxDirectores1.getSelectedItem().toString();
        String actor = jComboBoxActores1.getSelectedItem().toString();
        int anioInicioBusqueda; 
        anioInicioBusqueda = Integer.parseInt((String)jComboBoxAnioInferior1.
                                                             getSelectedItem());
        int anioFinalBusqueda;
        anioFinalBusqueda = Integer.parseInt((String)jComboBoxAnioSuperior1.
                                                             getSelectedItem());
        double puntajeIniBusqueda; 
        puntajeIniBusqueda = Double.parseDouble
                          ((String)jComboBoxPuntajeInferior1.getSelectedItem());
        double puntajeFinBusqueda;
        puntajeFinBusqueda = Double.parseDouble
                          ((String)jComboBoxPuntajeSuperior1.getSelectedItem());
        String genero = jComboBoxGenero1.getSelectedItem().toString();        
        Lista listaPeliculas; 
        listaPeliculas = UCUMovieGestor.peliculasPorTodosLosFiltros(director, 
                           actor, anioInicioBusqueda, anioFinalBusqueda, 
                                puntajeIniBusqueda, puntajeFinBusqueda, genero);
        
        DefaultListModel model = new DefaultListModel();
        jListResultBusqueda.setModel(model);
        
        if(listaPeliculas.esVacia() == true){
            model.addElement("La Búsqueda no ha arrojado ningún resultado");
        }else{
            INodo<Pelicula> auxiliar = listaPeliculas.getPrimero();        
            while (auxiliar != null){
                String a = auxiliar.getDato().getNombre();
                model.addElement(a);
                auxiliar = auxiliar.getSiguiente();
            }            
        }       
    }//GEN-LAST:event_jButtonBusquedaCriteriosVariosActionPerformed

    private void jListResultBusquedaDirectoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListResultBusquedaDirectoresMouseClicked
       String selected = (String)jListResultBusquedaDirectores.getSelectedValue();
        
        if (selected!=null){            
            String rutaAImagen = UCUMovieGestor.imagenPelicula(selected);
            InfoPeliculaDetallada infopelicula;         
           infopelicula = new InfoPeliculaDetallada(UCUMovieGestor.
                                     infoPelicula(selected), this, rutaAImagen);
            infopelicula.setVisible(true);            
        }  
    }//GEN-LAST:event_jListResultBusquedaDirectoresMouseClicked

    private void jListResultBusquedaActoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListResultBusquedaActoresMouseClicked
        String selected = (String)jListResultBusquedaActores.getSelectedValue();
        
        if (selected!=null){            
            String rutaAImagen = UCUMovieGestor.imagenPelicula(selected);
            InfoPeliculaDetallada infopelicula;         
            infopelicula = new InfoPeliculaDetallada(UCUMovieGestor.
                                    infoPelicula(selected), this, rutaAImagen);
            infopelicula.setVisible(true);            
        }  
    }//GEN-LAST:event_jListResultBusquedaActoresMouseClicked

    private void jListResultBusquedaGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListResultBusquedaGeneroMouseClicked
        String selected = (String)jListResultBusquedaGenero.getSelectedValue();
        
        if (selected!=null){            
            String rutaAImagen = UCUMovieGestor.imagenPelicula(selected);
            InfoPeliculaDetallada infopelicula;         
            infopelicula = new InfoPeliculaDetallada(UCUMovieGestor.
                                     infoPelicula(selected), this, rutaAImagen);
            infopelicula.setVisible(true);            
        }  
    }//GEN-LAST:event_jListResultBusquedaGeneroMouseClicked

    private void jListResultBusquedaAnioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListResultBusquedaAnioMouseClicked
        String selected = (String)jListResultBusquedaAnio.getSelectedValue();
        
        if (selected!=null){            
            String rutaAImagen = UCUMovieGestor.imagenPelicula(selected);
            InfoPeliculaDetallada infopelicula;         
            infopelicula = new InfoPeliculaDetallada(UCUMovieGestor.
                                     infoPelicula(selected), this, rutaAImagen);
            infopelicula.setVisible(true);            
        }  
    }//GEN-LAST:event_jListResultBusquedaAnioMouseClicked

    private void jListResultBusquedaPuntajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListResultBusquedaPuntajeMouseClicked
        String selected = (String)jListResultBusquedaPuntaje.getSelectedValue();
        
        if (selected!=null){            
            String rutaAImagen = UCUMovieGestor.imagenPelicula(selected);
            InfoPeliculaDetallada infopelicula;         
            infopelicula = new InfoPeliculaDetallada(UCUMovieGestor.
                                     infoPelicula(selected), this, rutaAImagen);
            infopelicula.setVisible(true);            
        }  
    }//GEN-LAST:event_jListResultBusquedaPuntajeMouseClicked

    private void jListResultBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListResultBusquedaMouseClicked
        String selected = (String)jListResultBusqueda.getSelectedValue();
        
        if (selected!=null && 
                      selected!= "La Búsqueda no ha arrojado ningún resultado"){
            
            String rutaAImagen = UCUMovieGestor.imagenPelicula(selected);
            InfoPeliculaDetallada infopelicula;         
            infopelicula = new InfoPeliculaDetallada(UCUMovieGestor.
                                    infoPelicula(selected), this, rutaAImagen);
            infopelicula.setVisible(true);            
        }  
    }//GEN-LAST:event_jListResultBusquedaMouseClicked

    private void jLabelImagenPeliculaEstreno1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImagenPeliculaEstreno1MouseClicked
        String selected = (String)jLabelNombreEstreno1.getText();
        
        if (selected!=null){            
            String rutaAImagen = UCUMovieGestor.imagenPelicula(selected);
            InfoPeliculaDetallada infopelicula;         
            infopelicula = new InfoPeliculaDetallada(UCUMovieGestor.
                                     infoPelicula(selected), this, rutaAImagen);
            infopelicula.setVisible(true);            
        }  
    }//GEN-LAST:event_jLabelImagenPeliculaEstreno1MouseClicked

    private void jLabelImagenPeliculaEstreno2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImagenPeliculaEstreno2MouseClicked
         String selected = (String)jLabelNombreEstreno2.getText();
        
        if (selected!=null){            
            String rutaAImagen = UCUMovieGestor.imagenPelicula(selected);
            InfoPeliculaDetallada infopelicula;         
             infopelicula = new InfoPeliculaDetallada(UCUMovieGestor.
                                     infoPelicula(selected), this, rutaAImagen);
            infopelicula.setVisible(true);            
        } 
    }//GEN-LAST:event_jLabelImagenPeliculaEstreno2MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UCUMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UCUMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UCUMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UCUMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UCUMovieFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarPorAnio;
    private javax.swing.JButton jButtonBuscarPorPuntaje;
    private javax.swing.JButton jButtonBusquedaCriteriosVarios;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JComboBox<String> jComboBoxActores;
    private javax.swing.JComboBox<String> jComboBoxActores1;
    private javax.swing.JComboBox<String> jComboBoxAnioInferior;
    private javax.swing.JComboBox<String> jComboBoxAnioInferior1;
    private javax.swing.JComboBox<String> jComboBoxAnioSuperior;
    private javax.swing.JComboBox<String> jComboBoxAnioSuperior1;
    private javax.swing.JComboBox<String> jComboBoxDirectores;
    private javax.swing.JComboBox<String> jComboBoxDirectores1;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JComboBox<String> jComboBoxGenero1;
    private javax.swing.JComboBox<String> jComboBoxPuntajeInferior;
    private javax.swing.JComboBox<String> jComboBoxPuntajeInferior1;
    private javax.swing.JComboBox<String> jComboBoxPuntajeSuperior;
    private javax.swing.JComboBox<String> jComboBoxPuntajeSuperior1;
    private javax.swing.JLabel jLabelAnioEstreno1;
    private javax.swing.JLabel jLabelAnioEstreno2;
    private javax.swing.JLabel jLabelBuscarPorPuntaje;
    private javax.swing.JLabel jLabelBusquedaActores;
    private javax.swing.JLabel jLabelBusquedaAnioDesde;
    private javax.swing.JLabel jLabelBusquedaAnioDesde1;
    private javax.swing.JLabel jLabelBusquedaAnioDesdeGeneral;
    private javax.swing.JLabel jLabelBusquedaAnioHastaGeneral;
    private javax.swing.JLabel jLabelBusquedaDirector;
    private javax.swing.JLabel jLabelBusquedaGeneral;
    private javax.swing.JLabel jLabelBusquedaGeneralActor;
    private javax.swing.JLabel jLabelBusquedaGeneralDirector;
    private javax.swing.JLabel jLabelBusquedaGeneralGenero;
    private javax.swing.JLabel jLabelBusquedaPorAnio;
    private javax.swing.JLabel jLabelBusquedaPorGenero;
    private javax.swing.JLabel jLabelBusquedaPuntajeDesde;
    private javax.swing.JLabel jLabelBusquedaPuntajeDesdeGeneral;
    private javax.swing.JLabel jLabelBusquedaPuntajeHasta;
    private javax.swing.JLabel jLabelBusquedaPuntajeHasta1;
    private javax.swing.JLabel jLabelEstrenoPuntaje;
    private javax.swing.JLabel jLabelEstrenoPuntaje1;
    private javax.swing.JLabel jLabelEstrenos1;
    private javax.swing.JLabel jLabelImagenPeliculaEstreno1;
    private javax.swing.JLabel jLabelImagenPeliculaEstreno2;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelNombreEstreno1;
    private javax.swing.JLabel jLabelNombreEstreno2;
    private javax.swing.JLabel jLabelPuntuacionEstreno1;
    private javax.swing.JLabel jLabelPuntuacionEstreno2;
    private javax.swing.JLabel jLabelTodasLasPeliculas;
    private javax.swing.JLabel jLabelUcuMovies;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList jListPeliculas;
    private javax.swing.JList<String> jListResultBusqueda;
    private javax.swing.JList<String> jListResultBusquedaActores;
    private javax.swing.JList<String> jListResultBusquedaAnio;
    private javax.swing.JList<String> jListResultBusquedaDirectores;
    private javax.swing.JList<String> jListResultBusquedaGenero;
    private javax.swing.JList<String> jListResultBusquedaPuntaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanelBusquedaActores;
    private javax.swing.JPanel jPanelBusquedaAnio;
    private javax.swing.JPanel jPanelBusquedaDirectores;
    private javax.swing.JPanel jPanelBusquedaGeneral;
    private javax.swing.JPanel jPanelBusquedaPorActor;
    private javax.swing.JPanel jPanelBusquedaPorActor1;
    private javax.swing.JPanel jPanelBusquedaPorAnio;
    private javax.swing.JPanel jPanelBusquedaPorAnio1;
    private javax.swing.JPanel jPanelBusquedaPorAnio2;
    private javax.swing.JPanel jPanelBusquedaPorAnio3;
    private javax.swing.JPanel jPanelBusquedaPorDirector;
    private javax.swing.JPanel jPanelBusquedaPorDirector1;
    private javax.swing.JPanel jPanelBusquedaPorGenero;
    private javax.swing.JPanel jPanelBusquedaPorPuntaje;
    private javax.swing.JPanel jPanelPaginaInicio;
    private javax.swing.JPanel jPanelPrincipalPeliculas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPanePrincipal;
    // End of variables declaration//GEN-END:variables
}
